title: Joseph Adebayo Pharm. D.
logo: "/images/Coach.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I use data analysis to drive process improvements, make better decisions, and achieve outcomes that enhance the bottom line.
  <br><br>
  <a href="https://www.linkedin.com/in/dr-joseph-adebayo/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
